services:
  - type: web
    name: my-web-service
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node src/index.js'
    envVars:
      - key: NODE_ENV
        value: production

  - type: worker
    name: my-cron-worker
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node cron/cron-job.js'
    envVars:
      - key: NODE_ENV
        value: production
